#!/usr/bin/env bash
#
# Compile blog-site/redirects.json into the CloudFront viewer-request function
# and publish it.
#
# The function does two jobs and the ORDER matters: redirect first, then rewrite.
# If the /slug/ -> /slug/index.html rewrite ran first, the redirect table would
# never match (it is keyed on the public URL, not the object key) and every
# retired post would 404 instead of forwarding.
#
# This script is the only thing that should ever write that function. It refuses
# to publish a function that fails its own local test, because a bad viewer
# function takes the ENTIRE site down at the edge — there is no partial failure.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
FN="blog-vodou-ai-rewrite"
SRC="blog-site/redirects.json"
BUILD="/tmp/cf-rewrite.js"

MAP=$(python3 -c "
import json; d=json.load(open('$SRC'))['redirects']
print(json.dumps(d, indent=2, sort_keys=True))
")

cat > "$BUILD" <<JSEOF
// GENERATED by scripts/blog/sync-redirects.sh from blog-site/redirects.json.
// Do not edit in the AWS console — the next sync overwrites it.
var REDIRECTS = $MAP;

function handler(event) {
    var request = event.request;
    var uri = request.uri;

    // 1. Permanent redirects, keyed on the PUBLIC url. Must run before the
    //    index rewrite below, or these keys can never match.
    var target = REDIRECTS[uri] || REDIRECTS[uri + '/'];
    if (target) {
        return {
            statusCode: 301,
            statusDescription: 'Moved Permanently',
            headers: {
                'location': { value: target },
                'cache-control': { value: 'public, max-age=3600' }
            }
        };
    }

    // 2. Directory-style URLs -> the object that actually exists in S3.
    //    An S3 REST origin has no index-document behaviour on subpaths, so
    //    without this every /slug/ returns AccessDenied (not 404 — the caller
    //    is not permitted to learn whether the key exists).
    if (uri.endsWith('/')) {
        request.uri = uri + 'index.html';
    } else if (!uri.includes('.')) {
        request.uri = uri + '/index.html';
    }
    return request;
}
JSEOF

# --- local test before anything reaches the edge -----------------------------
node - "$BUILD" <<'NODEEOF'
const fs = require('fs');
const src = fs.readFileSync(process.argv[2], 'utf8');
const handler = new Function(src + '; return handler;')();
const cases = [
  ['/prompt-caching-froze-my-system-prompt-so-my-edit-vanished/', 301],
  ['/prompt-caching-froze-my-system-prompt-so-my-edit-vanished',  301],
  ['/why-my-llm-agent-fabricated-numbers-from-stale-context/',    'rewrite'],
  ['/',            'rewrite'],
  ['/built/memory/', 'rewrite'],
  ['/llms.txt',    'passthrough'],
  ['/og/home.png', 'passthrough'],
];
let bad = 0;
for (const [uri, want] of cases) {
  const out = handler({ request: { uri, headers: {} } });
  let got;
  if (out.statusCode) got = out.statusCode;
  else if (out.uri !== uri) got = 'rewrite';
  else got = 'passthrough';
  const ok = got === want;
  if (!ok) bad++;
  console.log(`  ${ok ? 'ok  ' : 'FAIL'} ${uri}  -> ${got}${ok ? '' : ` (want ${want})`}`);
}
if (bad) { console.error(`${bad} case(s) failed — refusing to publish`); process.exit(1); }
console.log('all cases pass');
NODEEOF

ETAG=$(aws cloudfront describe-function --name "$FN" --query 'ETag' --output text)
echo "publishing function (etag $ETAG)"
NEW_ETAG=$(aws cloudfront update-function --name "$FN" --if-match "$ETAG" \
  --function-config Comment="blog.vodou.ai redirects + index rewrite",Runtime=cloudfront-js-2.0 \
  --function-code "fileb://$BUILD" --query 'ETag' --output text)
aws cloudfront publish-function --name "$FN" --if-match "$NEW_ETAG" \
  --query 'FunctionSummary.{Name:Name,Stage:FunctionMetadata.Stage,Status:Status}' --output json
echo "published."
