/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/automations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all automations */
        get: operations["automationsList"];
        put?: never;
        /** Create an automation */
        post: operations["automationsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/automations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get automation with last 50 run records */
        get: operations["automationsGet"];
        put?: never;
        post?: never;
        /** Delete an automation */
        delete: operations["automationsDelete"];
        options?: never;
        head?: never;
        /** Partial update of an automation */
        patch: operations["automationsUpdate"];
        trace?: never;
    };
    "/api/automations/{id}/reset-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear automation runtime state and last_error */
        post: operations["automationsResetState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/automations/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue automation for immediate execution (next worker tick ≤60s) */
        post: operations["automationsTrigger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brain/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute query through BrainLoader (full intent routing + tool execution) */
        post: operations["brainExecute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hooks */
        get: operations["hooksList"];
        put?: never;
        /** Create a hook */
        post: operations["hooksCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a hook */
        delete: operations["hooksRemove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hooks/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable or disable a hook */
        post: operations["hooksToggle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze query intent without executing */
        post: operations["intentsAnalyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/flush": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger session memory extraction */
        post: operations["memoryFlush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic memory search */
        post: operations["memorySearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback — exchanges code for token */
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save manual credentials for a server */
        post: operations["oauthCredentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke OAuth tokens and disconnect a server */
        post: operations["oauthRevoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin OAuth authorization flow — returns redirect_url */
        post: operations["oauthStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth connection status for all servers */
        get: operations["oauthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/switch-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear OAuth tokens and restart auth flow (switch account) */
        post: operations["oauthSwitchAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Routing feedback statistics (stub — full stats via /api/brain/execute) */
        get: operations["routingStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scheduled tasks */
        get: operations["scheduleList"];
        put?: never;
        /** Create a scheduled task */
        post: operations["scheduleAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a scheduled task */
        delete: operations["scheduleRemove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered MCP servers */
        get: operations["serversList"];
        put?: never;
        /** Register (upsert) an MCP server */
        post: operations["serversRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an MCP server */
        delete: operations["serversRemove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{name}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle server active status */
        patch: operations["serversSetActive"];
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available MCP tools */
        get: operations["toolsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Call an MCP tool directly */
        post: operations["toolsCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{tool_name}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single tool's JSON schema */
        get: operations["toolsSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Automation: {
            actions?: unknown[];
            created_at?: string;
            description?: string | null;
            enabled?: boolean;
            id?: number;
            interval_minutes?: number;
            last_error?: string | null;
            last_run_at?: string | null;
            name?: string;
            next_run_at?: string | null;
            notify?: Record<string, never> | null;
            post_to_chat?: boolean;
            run_count?: number;
            state?: Record<string, never>;
            trigger?: Record<string, never>;
            updated_at?: string | null;
        };
        AutomationRun: {
            actions_result?: Record<string, never> | null;
            error?: string | null;
            events_matched?: number;
            finished_at?: string | null;
            id?: number;
            started_at?: string;
            success?: boolean;
            trigger_result?: Record<string, never> | null;
        };
        ErrEnvelope: {
            error?: string;
            /** @enum {boolean} */
            ok?: false;
        };
        Hook: {
            enabled?: boolean;
            event_name?: string;
            hook_command?: string | null;
            hook_config?: Record<string, never> | null;
            hook_type?: string;
            id?: number;
            matcher_type?: string | null;
            matcher_value?: string | null;
            name?: string;
            priority?: number;
        };
        ScheduleTask: {
            command?: string;
            created_at?: string;
            cron?: string;
            enabled?: boolean;
            id?: number;
            last_run_at?: string | null;
            name?: string;
            next_run_at?: string | null;
        };
        Server: {
            active?: boolean;
            connection_config?: string | null;
            connection_type?: string;
            health?: string | null;
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    automationsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Automation list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            automations?: components["schemas"]["Automation"][];
                            count?: number;
                        };
                        ok?: boolean;
                    };
                };
            };
        };
    };
    automationsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default [] */
                    actions?: unknown[];
                    description?: string | null;
                    /** @default true */
                    enabled?: boolean;
                    /** @default 15 */
                    interval_minutes?: number;
                    name: string;
                    notify?: Record<string, never> | null;
                    /** @default false */
                    post_to_chat?: boolean;
                    trigger: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    automationsGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Automation + runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    automationsDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    automationsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    actions?: unknown[];
                    description?: string;
                    enabled?: boolean;
                    interval_minutes?: number;
                    name?: string;
                    notify?: Record<string, never>;
                    post_to_chat?: boolean;
                    trigger?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    automationsResetState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    automationsTrigger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    brainExecute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default false */
                    clean?: boolean;
                    query: string;
                };
            };
        };
        responses: {
            /** @description Execution result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["schemas"]["ErrEnvelope"];
        };
    };
    hooksList: {
        parameters: {
            query?: {
                /** @description Filter by event name */
                event?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hook list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            count?: number;
                            hooks?: components["schemas"]["Hook"][];
                        };
                        ok?: boolean;
                    };
                };
            };
        };
    };
    hooksCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default true */
                    enabled?: boolean;
                    event_name: string;
                    hook_command?: string | null;
                    hook_config?: Record<string, never> | null;
                    hook_type: string;
                    matcher_type?: string | null;
                    matcher_value?: string | null;
                    name: string;
                    /** @default 0 */
                    priority?: number;
                };
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hooksRemove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    hooksToggle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    intentsAnalyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                };
            };
        };
        responses: {
            /** @description Intent analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memoryFlush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    session_text?: string | null;
                };
            };
        };
        responses: {
            /** @description Flush queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memorySearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    scope?: string | null;
                    /** @default 10 */
                    top_k?: number;
                };
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            count?: number;
                            query?: string;
                            results?: unknown[];
                        };
                        ok?: boolean;
                    };
                };
            };
        };
    };
    oauthCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token stored; HTML success page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauthCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    credentials: Record<string, never>;
                    server_name: string;
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    oauthRevoke: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    server_name: string;
                };
            };
        };
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    oauthStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    server_name: string;
                };
            };
        };
        responses: {
            /** @description Auth URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-server OAuth status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauthSwitchAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    server_name: string;
                };
            };
        };
        responses: {
            /** @description Cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    routingStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scheduleList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            count?: number;
                            tasks?: components["schemas"]["ScheduleTask"][];
                        };
                        ok?: boolean;
                    };
                };
            };
        };
    };
    scheduleAdd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    command: string;
                    /** @description 5-field cron expression */
                    cron: string;
                    /** @default true */
                    enabled?: boolean;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scheduleRemove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    serversList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            count?: number;
                            servers?: components["schemas"]["Server"][];
                        };
                        ok?: boolean;
                    };
                };
            };
        };
    };
    serversRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    connection_type: Record<string, never>;
                    description?: string | null;
                    install_method?: string | null;
                    name: string;
                    tags?: string[] | null;
                };
            };
        };
        responses: {
            /** @description Registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    serversRemove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    serversSetActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    active: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    toolsList: {
        parameters: {
            query?: {
                server?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            count?: number;
                            tools?: unknown[];
                        };
                        ok?: boolean;
                    };
                };
            };
        };
    };
    toolsCall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default {} */
                    args?: Record<string, never>;
                    server: string;
                    tool: string;
                };
            };
        };
        responses: {
            /** @description Tool result with duration_ms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["schemas"]["ErrEnvelope"];
        };
    };
    toolsSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["schemas"]["ErrEnvelope"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        service?: string;
                        version?: string;
                    };
                };
            };
        };
    };
}
