-- 081_mcp_egress_audit.sql — what an attached MCP client actually did
-- (PLAN-MCP-EGRESS-MEMORY, "left for T2 completion", 2026-08-05).
--
-- T2 gave egress a subject: before it, every client presented the same token against a
-- server holding one profile and one vault, so "who called this" had no answer worth
-- recording. With `mcp_clients` in place each call has an identity, and this is the
-- ledger that names it.
--
-- The boundary this closes: a user can already see WHICH clients are attached (Settings
-- -> Clients) and revoke one. What they could not see is what an attached client read.
-- For a product whose claim is that your memory stays yours, "you may attach Cursor to
-- your brain" is only half a promise without "and here is what it looked at".
--
-- ## What is NOT stored, and why
--
-- Argument CONTENTS are never written. This table would otherwise become a second copy
-- of every question anyone ever asked the memory — a `vc_memory_search` log holding
-- query text is arguably more sensitive than the memory it searches, because it is a
-- record of what you were curious about, in order, with timestamps. So arguments are
-- reduced to a digest plus a byte count.
--
-- ## Why the digest is salted
--
-- A raw SHA-256 of a short argument is not confidential: "what is my dog named" has a
-- guessable digest, and anyone holding this file could confirm a hypothesis by hashing
-- it. The salt is per-install, random, and never leaves the machine, so a digest here
-- can still be correlated with other rows on THIS machine ("the same query ran 40
-- times") while telling an offline reader nothing about what the query was.
--
-- The salt is generated by SQLite at migration time; it is not derived from the console
-- token or any other credential, so rotating a secret does not silently invalidate the
-- correlation, and a leaked salt is not a leaked key.
--
-- ## Denials are rows too
--
-- An attempt on a withheld tool is the single most interesting event this table can
-- hold: it is the difference between "the profile is working" and "something attached
-- to your machine is probing for a shell". Recording only successes would omit exactly
-- the case a user would want to look up.

CREATE TABLE IF NOT EXISTS mcp_egress_audit (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    -- Matches mcp_clients.client_id, but deliberately NOT a foreign key: a revoked or
    -- deleted client must not take its history with it, and a stdio caller may name a
    -- client_id that was never registered (see mcp_audit::Subject).
    client_id    TEXT NOT NULL,
    label        TEXT,
    transport    TEXT NOT NULL,              -- 'stdio' | 'http'
    profile      TEXT NOT NULL,
    vault        TEXT NOT NULL,
    tool         TEXT NOT NULL,
    outcome      TEXT NOT NULL,              -- 'ok' | 'denied' | 'error'
    -- Salted SHA-256 of the canonicalised arguments. NEVER the arguments. NULL when the
    -- call carried none.
    args_digest  TEXT,
    -- Size of the arguments in bytes. Kept because volume is visible in a way content is
    -- not: a client suddenly sending 400KB of arguments is worth seeing without anyone
    -- having to store what it sent.
    arg_bytes    INTEGER NOT NULL DEFAULT 0,
    duration_ms  INTEGER,
    -- Naive UTC 'YYYY-MM-DD HH:MM:SS' per PLAN-TIME-CANON; compare with datetime(),
    -- render local at the display layer.
    at           TEXT NOT NULL DEFAULT (datetime('now'))
);

-- The two questions this table gets asked: "what happened recently" and "what did THIS
-- client do".
CREATE INDEX IF NOT EXISTS idx_mcp_audit_at ON mcp_egress_audit(at DESC);
CREATE INDEX IF NOT EXISTS idx_mcp_audit_client ON mcp_egress_audit(client_id, at DESC);
-- Denials are the rare row and the one worth finding fast.
CREATE INDEX IF NOT EXISTS idx_mcp_audit_outcome ON mcp_egress_audit(outcome, at DESC);

-- One row, created once. `id = 1` is enforced so a second salt cannot appear and split
-- the digest space in half without anyone noticing.
CREATE TABLE IF NOT EXISTS mcp_audit_meta (
    id       INTEGER PRIMARY KEY CHECK (id = 1),
    arg_salt TEXT NOT NULL
);
INSERT OR IGNORE INTO mcp_audit_meta (id, arg_salt) VALUES (1, lower(hex(randomblob(32))));
