-- 083: register the MCP servers that ship in the release but were never in the
-- upgrade path's mcp_servers table.
--
-- WHY
-- Fresh installs get their registry from the shipped vodou-core-clean.db, which
-- is generated by .build/scripts/create-clean-db.sh. That generator's server list
-- had drifted from the release packer's copy_server_prebuilt list, so five
-- servers shipped as directories with no row at all. The generator is fixed, but
-- that only helps NEW installs — an existing user who updates keeps their own
-- vodou-core.db and never sees the new rows. A server with no row is invisible:
-- the gateway won't connect it, `vodou-core call <server> …` can't find it, and
-- it never appears in Capabilities. For Vodou-Board that surfaced as board
-- workers being unable to call board_complete, so dispatched tasks looped until
-- they were reclaimed.
--
-- `brain` is already handled by migration 077, so it is not re-inserted here —
-- but 077 inserts it with a bare `node` command, which run_migration_083's
-- normalization step repairs (see database.rs). Same for the rows below: they
-- are written with `node` and normalized to the bundled `./.node/node` in the
-- same pass, because SQL cannot test whether the bundled runtime exists on this
-- machine and a source checkout has no .node/ directory.
--
-- INSERT OR IGNORE throughout: `name` is UNIQUE, so anyone who already has these
-- rows (or hand-patched them, as the fresh-install VM did) is left untouched.

-- Active on install: local, no credentials needed.
INSERT OR IGNORE INTO mcp_servers
    (name, command, args, connection_type, lifecycle_type, session_config, active, description)
VALUES
    ('Vodou-Board', 'node', '["MCP-servers/Vodou-Board/dist/index.js"]', 'stdio', 'ephemeral',
     '{"requires_session": false}', 1,
     'Multi-agent task board. board_* tools are gated on the VODOU_BOARD_TASK env var, so they are exposed only inside a dispatcher-spawned worker, never in normal chat.'),
    ('vodou-memory', 'node', '["MCP-servers/vodou-memory/index.js"]', 'stdio', 'ephemeral',
     '{"requires_session": false}', 1,
     'Vodou memory access for external MCP clients (IDEs). Entry point is index.js at the server root, not dist/index.js.');

-- Registered but INACTIVE: both need an OAuth flow before they can connect.
-- Shipping them active guarantees a failed first health-check and reconnect-loop
-- log spam (the dalle/uml-mcp incident). Mirrors how context7 ships. The router
-- joins on ms.active = 1, so their intent keywords stay dormant until enabled.
INSERT OR IGNORE INTO mcp_servers
    (name, command, args, connection_type, lifecycle_type, session_config, active, description)
VALUES
    ('gmail', 'node', '["MCP-servers/gmail/launcher.js"]', 'stdio', 'ephemeral',
     '{"requires_session": false}', 0,
     'Gmail MCP wrapper. Requires OAuth setup before activation.'),
    ('ms365', 'node', '["MCP-servers/ms365/launcher.js"]', 'stdio', 'ephemeral',
     '{"requires_session": false}', 0,
     'Microsoft 365 MCP wrapper (@softeria/ms-365-mcp-server). Requires OAuth setup before activation.');
