#!/usr/bin/env node

/**
 * {SERVER_NAME} - Custom MCP Server (Node.js)
 * Generated by Vodou MCP Builder
 * 
 * Description: {SERVER_DESCRIPTION}
 * Generated: {GENERATION_DATE}
 */

const { Server } = require('@modelcontextprotocol/sdk/server/index.js');
const { StdioServerTransport } = require('@modelcontextprotocol/sdk/server/stdio.js');
const {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListResourcesRequestSchema,
  GetResourceRequestSchema,
} = require('@modelcontextprotocol/sdk/types.js');
const fs = require('fs').promises;
const path = require('path');

// Custom imports based on requirements
{CUSTOM_IMPORTS}

class {CLASS_NAME}MCPServer {
  /**
   * Custom MCP Server: {SERVER_NAME}
   * 
   * Capabilities:
   * {SERVER_CAPABILITIES}
   */
  
  constructor() {
    this.server = new Server(
      {
        name: '{SERVER_NAME}',
        version: '{SERVER_VERSION}',
      },
      {
        capabilities: {
          tools: {},
          resources: {},
        },
      }
    );
    
    this.config = this.loadConfig();
    this.cache = new Map();
    this.setupHandlers();
    
    console.log(`Initialized {SERVER_NAME} MCP Server v{SERVER_VERSION}`);
  }

  loadConfig() {
    /**
     * Load configuration from environment variables and config file
     */
    const config = {
      serverName: '{SERVER_NAME}',
      version: '{SERVER_VERSION}',
      debug: process.env.DEBUG === 'true',
      // Custom configuration
      {SERVER_CONFIG}
    };

    // Load from config file if exists
    const configFile = path.join(__dirname, 'config', 'settings.json');
    try {
      if (require('fs').existsSync(configFile)) {
        const fileConfig = require(configFile);
        Object.assign(config, fileConfig);
        console.log(`Loaded configuration from ${configFile}`);
      }
    } catch (error) {
      console.warn(`Could not load config file: ${error.message}`);
    }

    return config;
  }

  setupHandlers() {
    /**
     * Register all MCP handlers
     */

    // List tools handler
    this.server.setRequestHandler(ListToolsRequestSchema, async () => {
      return {
        tools: [
          {TOOL_DEFINITIONS}
        ],
      };
    });

    // List resources handler
    this.server.setRequestHandler(ListResourcesRequestSchema, async () => {
      return {
        resources: [
          {RESOURCE_DEFINITIONS}
        ],
      };
    });

    // Tool call handlers
    this.server.setRequestHandler(CallToolRequestSchema, async (request) => {
      const { name, arguments: args } = request.params;
      
      try {
        switch (name) {
          {TOOL_CASES}
          default:
            throw new Error(`Unknown tool: ${name}`);
        }
      } catch (error) {
        console.error(`Error in tool ${name}:`, error);
        return {
          content: [
            {
              type: 'text',
              text: this.formatError(error),
            },
          ],
        };
      }
    });

    // Resource handlers
    this.server.setRequestHandler(GetResourceRequestSchema, async (request) => {
      const { uri } = request.params;
      
      try {
        {RESOURCE_HANDLERS}
        
        throw new Error(`Unknown resource: ${uri}`);
      } catch (error) {
        console.error(`Error getting resource ${uri}:`, error);
        throw error;
      }
    });

    console.log('Registered all MCP handlers');
  }

  // Tool implementations
  {TOOL_IMPLEMENTATIONS}

  // Resource implementations
  {RESOURCE_IMPLEMENTATIONS}

  // Utility methods
  validateInput(data, requiredFields) {
    /**
     * Validate input data has required fields
     */
    const missingFields = requiredFields.filter(field => !(field in data));
    if (missingFields.length > 0) {
      throw new Error(`Missing required fields: ${missingFields.join(', ')}`);
    }
    return true;
  }

  formatError(error) {
    /**
     * Format error messages consistently
     */
    let errorMsg = `Error in {SERVER_NAME}: ${error.message}`;
    if (this.config.debug) {
      errorMsg += `\nStack trace:\n${error.stack}`;
    }
    return errorMsg;
  }

  cacheResult(key, result, ttlSeconds = 300) {
    /**
     * Cache result with TTL
     */
    const expiresAt = Date.now() + (ttlSeconds * 1000);
    this.cache.set(key, {
      data: result,
      expiresAt,
    });
  }

  getCachedResult(key) {
    /**
     * Get cached result if still valid
     */
    const cached = this.cache.get(key);
    if (!cached) {
      return null;
    }

    if (Date.now() > cached.expiresAt) {
      this.cache.delete(key);
      return null;
    }

    return cached.data;
  }

  async cleanup() {
    /**
     * Cleanup resources on shutdown
     */
    console.log(`Shutting down {SERVER_NAME} MCP Server`);
    // Custom cleanup
    {CLEANUP_CODE}
  }

  async start() {
    /**
     * Start the MCP server
     */
    const transport = new StdioServerTransport();
    await this.server.connect(transport);
    
    console.log(`{SERVER_NAME} MCP Server started successfully`);
  }
}

// Example tool implementation
async function exampleTool(args) {
  /**
   * Example tool implementation
   * 
   * @param {Object} args - Tool arguments from MCP call
   * @returns {Object} Response content
   */
  
  // Validate input
  this.validateInput(args, ['required_param']);
  
  // Get parameters
  const param1 = args.required_param;
  const param2 = args.optional_param || 'default_value';
  
  // Check cache first
  const cacheKey = `example_tool_${param1}_${param2}`;
  const cachedResult = this.getCachedResult(cacheKey);
  if (cachedResult) {
    console.log(`Returning cached result for ${cacheKey}`);
    return {
      content: [
        {
          type: 'text',
          text: cachedResult,
        },
      ],
    };
  }
  
  // Tool logic implementation
  console.log(`Executing example_tool with param1='${param1}', param2='${param2}'`);
  
  // Example implementation
  const result = {
    status: 'success',
    data: {
      param1,
      param2,
      timestamp: new Date().toISOString(),
      server: '{SERVER_NAME}',
    },
  };
  
  // Cache the result
  const resultJson = JSON.stringify(result, null, 2);
  this.cacheResult(cacheKey, resultJson);
  
  return {
    content: [
      {
        type: 'text',
        text: resultJson,
      },
    ],
  };
}

// Server startup
async function main() {
  try {
    const server = new {CLASS_NAME}MCPServer();
    
    // Setup graceful shutdown
    process.on('SIGINT', async () => {
      console.log('Received SIGINT, shutting down...');
      await server.cleanup();
      process.exit(0);
    });
    
    process.on('SIGTERM', async () => {
      console.log('Received SIGTERM, shutting down...');
      await server.cleanup();
      process.exit(0);
    });
    
    // Start server
    await server.start();
    
  } catch (error) {
    console.error('Failed to start server:', error);
    process.exit(1);
  }
}

// Run if this is the main module
if (require.main === module) {
  main().catch((error) => {
    console.error('Unhandled error:', error);
    process.exit(1);
  });
}

module.exports = { {CLASS_NAME}MCPServer };