#!/bin/bash

# Vodou Morning Brief Generator
# Gathers intelligence from multiple sources and generates daily brief

# Resolve project root relative to script location (works on any machine)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${VODOU_PROJECT_PATH:-$(cd "$SCRIPT_DIR" && while [ ! -f vodou-core ] && [ "$(pwd)" != "/" ]; do cd ..; done && pwd)}"
BRAIN_TRUST="$PROJECT_ROOT/vodou-core"
OUTPUT_DIR="$PROJECT_ROOT/briefs"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
BRIEF_FILE="$OUTPUT_DIR/morning-brief-$TIMESTAMP.md"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Start building the brief
cat > "$BRIEF_FILE" << 'HEADER'
# 🌅 Vodou Morning Brief

---

HEADER

# Add date and time
echo "**Generated:** $(date '+%A, %B %d, %Y at %I:%M %p')" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "---" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# System Health Section
echo "## ⚙️ System Health" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# Get CPU info
CPU_INFO=$($BRAIN_TRUST call mcp-monitor get_cpu_info '{}' 2>/dev/null)
if [ $? -eq 0 ]; then
    echo "### 💻 CPU" >> "$BRIEF_FILE"
    echo "\`\`\`" >> "$BRIEF_FILE"
    echo "$CPU_INFO" | grep -E "(model|cores|usage|speed)" >> "$BRIEF_FILE"
    echo "\`\`\`" >> "$BRIEF_FILE"
    echo "" >> "$BRIEF_FILE"
fi

# Get Memory info
MEM_INFO=$($BRAIN_TRUST call mcp-monitor get_memory_info '{}' 2>/dev/null)
if [ $? -eq 0 ]; then
    echo "### 🧠 Memory" >> "$BRIEF_FILE"
    echo "\`\`\`" >> "$BRIEF_FILE"
    echo "$MEM_INFO" | grep -E "(total|used|available|percentage)" >> "$BRIEF_FILE"
    echo "\`\`\`" >> "$BRIEF_FILE"
    echo "" >> "$BRIEF_FILE"
fi

# Get Disk info
DISK_INFO=$($BRAIN_TRUST call mcp-monitor get_disk_info '{}' 2>/dev/null)
if [ $? -eq 0 ]; then
    echo "### 💾 Disk" >> "$BRIEF_FILE"
    echo "\`\`\`" >> "$BRIEF_FILE"
    echo "$DISK_INFO" | grep -E "(total|used|free|percentage)" | head -4 >> "$BRIEF_FILE"
    echo "\`\`\`" >> "$BRIEF_FILE"
    echo "" >> "$BRIEF_FILE"
fi

echo "---" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# Memory Insights Section
echo "## 🧠 Recent Memory Insights" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# Search for recent memories about Vodou, projects, or important topics
MEMORIES=$($BRAIN_TRUST mem search "Vodou projects ideas" 2>/dev/null)
if [ $? -eq 0 ] && [ -n "$MEMORIES" ]; then
    echo "$MEMORIES" | head -10 >> "$BRIEF_FILE"
    echo "" >> "$BRIEF_FILE"
else
    echo "*No recent memory insights available.*" >> "$BRIEF_FILE"
    echo "" >> "$BRIEF_FILE"
fi

echo "---" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# Daily Focus Section
echo "## 💡 Suggested Focus for Today" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "Based on your system status and recent activity:" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# Simple logic based on system stats
DISK_USAGE=$(echo "$DISK_INFO" | grep -oE "[0-9]+\.[0-9]+%" | head -1 | sed 's/%//')
MEM_USAGE=$(echo "$MEM_INFO" | grep -oE "[0-9]+\.[0-9]+%" | head -1 | sed 's/%//')

if (( $(echo "$DISK_USAGE > 80" | bc -l 2>/dev/null || echo 0) )); then
    echo "- ⚠️ **Disk Cleanup**: Your disk is at ${DISK_USAGE}% - consider cleaning up old files" >> "$BRIEF_FILE"
fi

if (( $(echo "$MEM_USAGE > 85" | bc -l 2>/dev/null || echo 0) )); then
    echo "- ⚠️ **Memory Management**: Memory usage is high at ${MEM_USAGE}% - consider closing unused apps" >> "$BRIEF_FILE"
fi

echo "- ✅ **Continue Building**: Keep developing Vodou capabilities and skills" >> "$BRIEF_FILE"
echo "- 🚀 **Test Automation**: Set up scheduled execution of this brief" >> "$BRIEF_FILE"
echo "- 🔧 **Expand Data Sources**: Add calendar, weather, or custom integrations" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

echo "---" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# Footer
echo "## 🎯 Next Steps" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "1. Review system health metrics above" >> "$BRIEF_FILE"
echo "2. Address any warnings or alerts" >> "$BRIEF_FILE"
echo "3. Focus on suggested priorities" >> "$BRIEF_FILE"
echo "4. Customize this brief by editing \`generate-morning-brief.sh\`" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "---" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "*🤖 Generated by Vodou Morning Brief - Your Personal Intelligence System*" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "**Brief saved to:** \`$BRIEF_FILE\`" >> "$BRIEF_FILE"

# Output the brief location
echo "✅ Morning Brief generated successfully!"
echo "📄 Location: $BRIEF_FILE"
echo ""
echo "To view: cat \"$BRIEF_FILE\""
echo "To open: open \"$BRIEF_FILE\""

# Also output to stdout for immediate viewing
cat "$BRIEF_FILE"
